# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply a number by three
#'
#' @param x A single integer.
#' @export
timesThree <- function(x) {
    .Call(`_q2e_timesThree`, x)
}

#' Run q2e via datafiles as in the C++ code
#'
#' @param paramFile the parameter file
rq2e <- function(argVector, fnVector, Rnreplicates) {
    .Call(`_q2e_rq2e`, argVector, fnVector, Rnreplicates)
}

